[tool.poetry]
name = "rag-chatbot"
version = "0.1.0"
description = ""
authors = ["Madhav Girish Nair <madhavgirish02@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.1"
gemini-api = "^0.1.6"
langchain = "^0.3.15"
clickhouse-connect = "^0.8.14"
langchain-community = "^0.3.15"
pypdf = "^5.1.0"
pandas = "^2.2.3"
black = "^25.1.0"
isort = "^6.0.1"
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
pydantic = "^2.11.4"
langchain-core = "^0.3.58"
langchain-chroma = "^0.2.3"
langchain-openai = "^0.3.16"
langchain-google-genai = "^2.1.4"
langchain-anthropic = "^0.3.12"
langchain-aws = "^0.2.22"
mangum = "^0.19.0"
aws-cdk-lib = "2.190.0"
constructs = ">=10.0.0,<11.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
